name: Windows Build (PyInstaller + Inno Setup)
on:
  push:
    branches: [ main ]
    paths:
      - "gui.py"
      - "src/**"
      - "requirements.txt"
      - "installer.iss"
      - ".github/workflows/windows-build.yml"
  workflow_dispatch: {}
jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pyinstaller
      - name: Build EXE with PyInstaller
        run: |
          pyinstaller --noconsole --onefile ^
            --name EtiquettesCSN ^
            --add-data "src\\app\\templates;src\\app\\templates" ^
            gui.py
        shell: cmd
      - uses: actions/upload-artifact@v4
        with:
          name: EtiquettesCSN-exe
          path: dist/EtiquettesCSN.exe
      - name: Install Inno Setup
        run: choco install -y innosetup
      - name: Build Installer (Inno Setup)
        run: |
          "C:\Program Files (x86)\Inno Setup 6\ISCC.exe" installer.iss
        shell: cmd
      - uses: actions/upload-artifact@v4
        with:
          name: Setup_EtiquettesCSN
          path: Output/Setup_EtiquettesCSN.exe
